### ISSUE TITLE
acitvity 1

### ISSUE THREAD

**Issue by sanamgill** [rosslaird/CRWR1100#2]
Could you please provide feedback for my first activity, and I have read the instructions but would like to make sure that I am doing this correctly as it is difficult to navigate.

**Comment by sanamgill** [comment]
r @rosslaird

**Comment by rosslaird** [comment]
I will provide feedback. But first you have to get this working properly. You have forked my repository instead of creating your own. Please use the link I sent in the email yesterday to create your own repository. Details about this are in the course outline.

**Comment by rosslaird** [comment]
Use this link to create your own repository:

https://classroom.github.com/a/jB-3oioB

**Comment by sanamgill** [comment]
Thank you!
